### ISSUE TITLE
install fails on resigned 'trans-org' enterprise app - archived-expanded-entitlements.xcent not updated

### ISSUE THREAD

**Issue by astletron** [felipesabino/provise#7]
Firstly - thanks for provise.  Been using it happily for a bit when resigning apps from within an organization.

Having some trouble trying to resign an app between organizations.

Process goes like this:
1. Compile an IPA with an explicit bundle id and matching MPP, with push notifications enabled and configured, and signed with an 'in-house' (enterprise) key.  This IPA installs correctly and recieves push notifications as expected.
2. Call resign using a certificate and MPP from another developer org enrolled in the apple enterprise dev program while changing bundle id to match new MPP.  Completes without error.
3. Attempt OTA installation of the new IPA.  This fails with:

Mar 25 12:03:33 Michaels-iPad itunesstored[2512] <Error>: 0x20bf000 __MobileInstallationInstallForLaunchServices_block_invoke240: Returned error Error Domain=MIInstallerErrorDomain Code=63 "Application is missing the application-identifier entitlement." UserInfo=0x145c0c60 {LegacyErrorString=ApplicationVerificationFailed, FunctionName=-[MIInstallableBundle performVerificationWithError:], NSLocalizedDescription=Application is missing the application-identifier entitlement., SourceFileLine=473}

---

In the resigned IPA, the correct NEW app id and bundle id appear in embedded.mobileprovision file under 'Entitlements' -> 'application-identifier'.  The file 'archived-expanded-entitlements.xcent' in the new IPA still contains references to the old app id and bundle id, though.   I >think< this is why the device declines to install the IPA.

**Comment by felipesabino** [comment]
@astletron Can you confirm this happens in the latest `0.0.3` version? And also, what XCode version are you using to build it?

I never experience such error but to be honest, I was never able to test between 2 enterprise accounts (I don't have access to one :disappointed: ).

If I could guess I would say that I have to add [--entitlements](https://developer.apple.com/library/mac/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html#//apple_ref/doc/uid/TP40005929-CH4-SW4) as an extra parameter to the [`codesign` command](https://github.com/felipesabino/provise/blob/1fc58b67a7952feb20ba31210312ab9ddec7965b/lib/provise/commands/ipa.rb#L63-L67)

**Comment by astletron** [comment]
Problem was not related to archived-expanded-entitlements.xcent.

I created an entitlements.xml file by hand and added --entitlementsFile to my use of 'resign ipa' and the resultant .ipa installed and worked just fine.

Would be nice to automate updating entitlements.  Some of those values are specific to the new app id and bundle id.

**Comment by felipesabino** [comment]
Oh, glad to hear it is working properly.

I will close this for now, then.

**Comment by felipesabino** [comment]
@astletron quick question: do you have push notifications enabled for this specific app you are resigning? are they working properly after resigning?
